repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: git://github.com/agmalpartida/pre-commit-hooks
    rev: v1.0.0
    hooks:
        - id: terraform-fmt
